name: Build & Update Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # You can use 'temurin', 'adopt', 'zulu', etc.
          java-version: '17'        # Use your project's required Java version

      - name: Generate Javadoc
        run: ./generate-docs.sh

      - name: Commit and Push Docs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/
          git commit -m "Automated docs update [skip ci]" || echo "No changes to commit"
          git push

