name: Build & Update Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Generate Javadoc
        run: mvn clean verify javadoc:javadoc

      - name: Commit and Push Docs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add target/site/apidocs/
          git commit -m "Automated docs update [skip ci]" || echo "No changes to commit"
          git push